matrix: Matrix< T, Value > Class Template Reference
Matrix< T, Value > Class Template Reference
Matrix
#include <matrix.h>
Classes
class Iterator
class MatrixElement
Public Member Functions
Iterator begin ()
Iterator's method for begin.
Iterator end ()
Iterator's method for end.
size_t size ()
Method for get number of non-default avaliable MatrixElements.
MatrixElement & operator[] (size_t index)
Operator for get created MatrixElement or create new MatrixElement by it's index.
Private Types
using elements_iterator = typename std::list< MatrixElement * >::iterator
Define type of _elements iterator for Iterator class .
Private Attributes
std::unordered_map< size_t, std::shared_ptr< MatrixElement > > _elements_storage
Field contain MatrixElement's first layer sisters/brothers.
std::shared_ptr< std::list< MatrixElement * > > _elements { std::make_shared<std::list<MatrixElement*>>() }
Field contain current non-default MatrixElements.
Friends
class Iterator
Set Iterator class as friend to Matrix class.
Detailed Description
template<class T, T Value>
class Matrix< T, Value >
Definition at line 25 of file matrix.h.
Member Typedef Documentation
elements_iterator
template<class T , T Value> using Matrix< T, Value >::elements_iterator = typename std::list<MatrixElement*>::iterator private
Define type of _elements iterator for Iterator class .
Definition at line 189 of file matrix.h.
Member Function Documentation
begin()
template<class T , T Value> Iterator Matrix< T, Value >::begin () inline
Iterator's method for begin.
Definition at line 282 of file matrix.h.
    {
        return Iterator(std::make_shared<elements_iterator>(_elements->begin()));
    }
end()
template<class T , T Value> Iterator Matrix< T, Value >::end () inline
Iterator's method for end.
Definition at line 290 of file matrix.h.
    {
        return Iterator(std::make_shared<elements_iterator>(_elements->end()));
    }
operator[]()
template<class T , T Value> MatrixElement & Matrix< T, Value >::operator[] (size_t index) inline
Operator for get created MatrixElement or create new MatrixElement by it's index.
Parameters
index is MatrixElement's index.
Returns
Reference to MatrixElement.
Definition at line 309 of file matrix.h.
    {
        try
        {
            return *_elements_storage.at(index);
        }
        catch (std::out_of_range e)
        {
            _elements_storage.insert(std::pair<size_t, std::shared_ptr<MatrixElement>>(index, std::make_shared<MatrixElement>(Value, index, nullptr, _elements)));
            return *_elements_storage.at(index);
        }
    }
size()
template<class T , T Value> size_t Matrix< T, Value >::size () inline
Method for get number of non-default avaliable MatrixElements.
Returns
Number of non-default avaliable MatrixElements.
Definition at line 299 of file matrix.h.
    {
        return _elements->size();
    }
Referenced by main().
Friends And Related Function Documentation
Iterator
template<class T , T Value> friend class Iterator friend
Set Iterator class as friend to Matrix class.
Definition at line 277 of file matrix.h.
Member Data Documentation
_elements
template<class T , T Value> std::shared_ptr<std::list<MatrixElement*> > Matrix< T, Value >::_elements { std::make_shared<std::list<MatrixElement*>>() } private
Field contain current non-default MatrixElements.
Definition at line 184 of file matrix.h.
Referenced by Matrix< T, Value >::begin(), Matrix< T, Value >::end(), Matrix< T, Value >::operator[](), and Matrix< T, Value >::size().
_elements_storage
template<class T , T Value> std::unordered_map<size_t, std::shared_ptr<MatrixElement> > Matrix< T, Value >::_elements_storage private
Field contain MatrixElement's first layer sisters/brothers.
Definition at line 179 of file matrix.h.
Referenced by Matrix< T, Value >::operator[]().
The documentation for this class was generated from the following file:
matrix.h